apiVersion: v1
kind: Pod
metadata:
  name: volume-pod
spec:
  containers:
  - name: busybox
    image: busybox
    command: ['sh', '-c', 'while true; do sleep 3600; done']
    volumeMounts:
      - name: configmap-volume
        mountPath: /etc/config/configmap
      - name: secret-volume
        mountPath: /etc/config/secret
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
  volumes:
    - name: configmap-volume
      configMap:
        name: my-configmap
    - name: secret-volume 
      secret:
        secretName: my-secret 
