apiVersion: v1
kind: Service 
metadata: 
  name: nodeport-service 
  labels:
    app: service
spec:
  type: NodePort
  ports:
    - nodePort: 32000 #used to access this service from outside the cluster
    - port: 80 
      targetPort: 80
  selector:
    app: app-server