apiVersion: v1
kind: Service 
metadata: 
  name: clusterip-service 
  labels:
    app: service
spec:
  ports:
    - port: 80 #other pods use port80 to access this service
      protocol: TCP
  selector:
    app: app-server