apiVersion: apps/v1
kind: Deployment 
metadata:
  labels:
    app: app-server
  name: clusterip-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-server
  minReadySeconds: 30
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: app-server
    spec:
      containers:
        - image: nginx:1.17
          name: webserver
          ports:
            - containerPort: 80 #pod recieving traffic from port 80