# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "dev" do |dev|
    dev.vm.box = "centos/7"
    dev.vm.network "public_network", ip: "192.168.1.90"
  end

  config.vm.provider "virtualbox" do |vb|
    vb.gui = true 
  end
end
