version: "3" 
services:
   web:
     image: nginx 

   db: 
     platform: linux/x86_64
     image: mysql 
     ports:
       - "3306:3306"
     environment:
       - MYSQL_ROOT_PASSWORD=password
       - MYSQL_USER=user
       - MYSQL_PASSWORD=password
       - MYSQL_DATABASE=database 